### ISSUE TITLE
List Features/ Bug resolutions/ Payment methods present in web but not in mobile

### ISSUE THREAD

**Issue by akash-c-k** [juspay/hyperswitch-client-core#30]

**Comment by aashu331998** [comment]
list of Features/ Bug resolutions/ Payment methods present in web but not in mobile
https://docs.google.com/spreadsheets/d/1Y9jP7nsoyYgOugPKN-CqTXWUFCiqrjOsfLOZLhJDwQg/edit?gid=0#gid=0
